language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: apbostic 
  api: https://api.run.pivotal.io
  organization: SASCloudFoundry
  space: development
